Setting up Otpim: SGD
lr: <function constant_fn.<locals>.func at 0x00000283F7665550>
other params: {}
GL HF! :)
Traceback (most recent call last):
  File "C:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 317, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] Die Pipe wurde beendet
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\tzehl\OneDrive\Dokumente\GitHub\Stauby-the-Rocket-League-Bot\train.py", line 53, in <module>
    model.learn(total_timesteps=1e7, callback=callback)
  File "C:\Users\tzehl\OneDrive\Dokumente\GitHub\schmalegg_hbf_abfahrt\venv\lib\site-packages\stable_baselines3\ppo\ppo.py", line 299, in learn
    return super(PPO, self).learn(
  File "C:\Users\tzehl\OneDrive\Dokumente\GitHub\schmalegg_hbf_abfahrt\venv\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 237, in learn
    continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
  File "C:\Users\tzehl\OneDrive\Dokumente\GitHub\schmalegg_hbf_abfahrt\venv\lib\site-packages\stable_baselines3\common\on_policy_algorithm.py", line 178, in collect_rollouts
    new_obs, rewards, dones, infos = env.step(clipped_actions)
  File "C:\Users\tzehl\OneDrive\Dokumente\GitHub\schmalegg_hbf_abfahrt\venv\lib\site-packages\stable_baselines3\common\vec_env\base_vec_env.py", line 162, in step
    return self.step_wait()
  File "C:\Users\tzehl\OneDrive\Dokumente\GitHub\schmalegg_hbf_abfahrt\venv\lib\site-packages\stable_baselines3\common\vec_env\vec_monitor.py", line 76, in step_wait
    obs, rewards, dones, infos = self.venv.step_wait()
  File "C:\Users\tzehl\OneDrive\Dokumente\GitHub\schmalegg_hbf_abfahrt\venv\lib\site-packages\stable_baselines3\common\vec_env\vec_normalize.py", line 114, in step_wait
    obs, rewards, dones, infos = self.venv.step_wait()
  File "C:\Users\tzehl\OneDrive\Dokumente\GitHub\schmalegg_hbf_abfahrt\venv\lib\site-packages\rlgym_tools\sb3_utils\sb3_multiple_instance_env.py", line 155, in step_wait
    obs, rew, done, info = remote.recv()
  File "C:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 255, in recv
    buf = self._recv_bytes()
  File "C:\Users\tzehl\AppData\Local\Programs\Python\Python39\lib\multiprocessing\connection.py", line 326, in _recv_bytes
    raise EOFError
EOFError